models/Order.php
<?php
/**
 * Created by PhpStorm.
 * User: dell
 * Date: 17.01.17
 * Time: 17:17
 */

namespace app\models;

use app\models\Product;
use app\models\Service;

class Order extends \yii\db\ActiveRecord
{

    public function rules()
    {
        return [
            ['quantity', 'integer', 'min' => 1]
        ];
    }

    public function getUser(){
        /*ToDo

        Add relation Order->User with hasOne() function

         return $this->hasOne(User::className(), ['id' => 'user_id']);
        */
    }
    public function  getProfile(){
        return $this->hasOne(Profile::className(), ['user_id' => 'user_id']);
    }

    public function getProduct(){

        return $this->hasOne(Product::className(), ['id' => 'product_id']);

    }
    public function getService(){

        return $this->hasOne(Service::className(), ['id' => 'serv_id']);

    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID замовлення',
            'date' => 'Дата замовлення',
            'user_id' => 'Користувач/ID користувача',
            'product_id' => 'Продукт/ID продукту',
            'quantity' => 'Кількість',
            'summ' => 'Всьго'
        ];
    }

}

controllers/SettingsController.php
<?php

namespace app\controllers;

use app\models\Order;
use Yii;

use dektrium\user\controllers\SettingsController as BaseSettingsController;

class SettingsController extends BaseSettingsController
{

    public function behaviors() {

        $param = parent::behaviors();
        
        $param['access']['rules'][0]['actions'][] = 'orders';
        return $param;
    }

    public function actionOrders() {
    	$authorized_user_id = Yii::$app->user->id;
    	$product_user = Order::find()->select('date, user_id, product_name, product_price, product_serv_id, SUM(quantity) AS quantity')->groupBy(['date', 'user_id','product_name', 'product_price', 'product_serv_id' ])->asArray()->where(['user_id' => $authorized_user_id])->orderBy(['date' => SORT_DESC])->all();

    	foreach ($product_user as $key => $value) {
			$product_user_in_date[$value['date']][]=$value;
		}
        
    	return $this->render('orders', compact('product_user_in_date'));
    }

}

views/settings/_menu.php
<?php

/*
 * This file is part of the Dektrium project.
 *
 * (c) Dektrium project <http://github.com/dektrium>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

use yii\helpers\Html;
use yii\widgets\Menu;

/**
 * @var dektrium\user\models\User $user
 */

$user = Yii::$app->user->identity;
$networksVisible = count(Yii::$app->authClientCollection->clients) > 0;
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <?= Html::img($user->profile->getAvatarUrl(24), [
                'class' => 'img-rounded',
                'alt' => $user->username,
            ]) ?>
            <?= $user->username ?>
        </h3>
    </div>
    <div class="panel-body">
        <?= Menu::widget([
            'options' => [
                'class' => 'nav nav-pills nav-stacked',
            ],
            'items' => [
                ['label' => Yii::t('user', 'Мої замовлення'), 'url' => ['/user/settings/orders']],
                //['label' => Yii::t('user', 'Мої замовлення'), 'url' => ['/user/settings/orders']],
                ['label' => Yii::t('user', 'Профіль'), 'url' => ['/user/settings/profile']],
                ['label' => Yii::t('user', 'Аккаунт'), 'url' => ['/user/settings/account']],
                [
                    'label' => Yii::t('user', 'Соціальні мережі'),
                    'url' => ['/user/settings/networks'],
                    'visible' => $networksVisible
                ],
            ],
        ]) ?>
    </div>
</div>

views/settings/account.php
<?php

/*
 * This file is part of the Dektrium project.
 *
 * (c) Dektrium project <http://github.com/dektrium>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var yii\widgets\ActiveForm $form
 * @var dektrium\user\models\SettingsForm $model
 */

$this->title = Yii::t('user', 'Налаштування аккаунту');
$this->params['breadcrumbs'][] = $this->title;
?>

<?= $this->render('/_alert', ['module' => Yii::$app->getModule('user')]) ?>

<div class="row">
    <div class="col-md-3">
        <?= $this->render('_menu') ?>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="panel-body">
                <?php $form = ActiveForm::begin([
                    'id' => 'account-form',
                    'options' => ['class' => 'form-horizontal'],
                    'fieldConfig' => [
                        'template' => "{label}\n<div class=\"col-lg-9\">{input}</div>\n<div class=\"col-sm-offset-3 col-lg-9\">{error}\n{hint}</div>",
                        'labelOptions' => ['class' => 'col-lg-3 control-label'],
                    ],
                    'enableAjaxValidation' => true,
                    'enableClientValidation' => false,
                ]); ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'username')->label('Логін') ?>

                <?= $form->field($model, 'new_password')->passwordInput()->label('Новий пароль') ?>

                <hr/>

                <?= $form->field($model, 'current_password')->passwordInput()->label('Поточний пароль') ?>

                <div class="form-group">
                    <div class="col-lg-offset-3 col-lg-9">
                        <?= Html::submitButton('Зберегти', ['class' => 'btn btn-block btn-success']) ?><br>
                    </div>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>

        <?php if ($model->module->enableAccountDelete): ?>
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= Yii::t('user', 'Delete account') ?></h3>
                </div>
                <div class="panel-body">
                    <p>
                        <?= Yii::t('user', 'Once you delete your account, there is no going back') ?>.
                        <?= Yii::t('user', 'It will be deleted forever') ?>.
                        <?= Yii::t('user', 'Please be certain') ?>.
                    </p>
                    <?= Html::a(Yii::t('user', 'Delete account'), ['delete'], [
                        'class' => 'btn btn-danger',
                        'data-method' => 'post',
                        'data-confirm' => Yii::t('user', 'Are you sure? There is no going back'),
                    ]) ?>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>

views/settings/networks.php
<?php

/*
 * This file is part of the Dektrium project.
 *
 * (c) Dektrium project <http://github.com/dektrium>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

use dektrium\user\widgets\Connect;
use yii\helpers\Html;

/**
 * @var $this yii\web\View
 * @var $form yii\widgets\ActiveForm
 */

$this->title = "Соціальні мережі";
$this->params['breadcrumbs'][] = $this->title;
?>

<?= $this->render('/_alert', ['module' => Yii::$app->getModule('user')]) ?>

<div class="row">
    <div class="col-md-3">
        <?= $this->render('_menu') ?>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?= Html::encode($this->title) ?>
            </div>
            <div class="panel-body">
                <div class="alert alert-info">
                    <p><?= Yii::t('user', 'You can connect multiple accounts to be able to log in using them') ?>.</p>
                </div>
                <?php $auth = Connect::begin([
                    'baseAuthUrl' => ['/user/security/auth'],
                    'accounts' => $user->accounts,
                    'autoRender' => false,
                    'popupMode' => false,
                ]) ?>
                <table class="table">
                    <?php foreach ($auth->getClients() as $client): ?>
                        <tr>
                            <td style="width: 32px; vertical-align: middle">
                                <?= Html::tag('span', '', ['class' => 'auth-icon ' . $client->getName()]) ?>
                            </td>
                            <td style="vertical-align: middle">
                                <strong><?= $client->getTitle() ?></strong>
                            </td>
                            <td style="width: 120px">
                                <?= $auth->isConnected($client) ?
                                    Html::a(Yii::t('user', 'Disconnect'), $auth->createClientUrl($client), [
                                        'class' => 'btn btn-danger btn-block',
                                        'data-method' => 'post',
                                    ]) :
                                    Html::a(Yii::t('user', 'Connect'), $auth->createClientUrl($client), [
                                        'class' => 'btn btn-success btn-block',
                                    ])
                                ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
                <?php Connect::end() ?>
            </div>
        </div>
    </div>
</div>

views/settings/orders.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Product;
use app\models\Service;
use yii\helpers\Url;

$this->title = Yii::t('user', 'Мої замовлення');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-md-3">
        <?= $this->render('_menu') ?>
    </div>
    <div class="col-md-9">
    	<div class="panel panel-default">
		    <div class="panel-heading">
	            <h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
	        </div>
	        <div class="panel-body">
                <?php if(isset($product_user_in_date)) { ?>
	        	<div class="clearfix">
                    <?php if( count($product_user_in_date) > 1 ) { ?>
                    <div class="all_user_order_block_slide">
                        <span>Розгорнути всі</span>
                    </div>
                    <?php } ?>
                </div>
                <ul class='product_user'>
                	<?php foreach($product_user_in_date as $keys => $values): ?>
	                <li class="admin_order_one">
                        <div class="user_order_block_up">
                            <div class="user_name">
                                <p><?=  date("d.m.Y", strtotime($keys)) ?></p>
                            </div>
                        </div>
                        <div class="table-responsive user_order_block_dn">
                            <table class="table table-hover ">
                                <thead>
                                <tr>
                                    <th>Назва товару</th>
                                    <th>Ціна</th>
                                    <th>Кількість</th>
                                    <th>Всього</th>
                                    <th>Сервіс</th>
                                </tr>
                                </thead>
                                <?php
                                    $summ_all = 0;
                                    foreach ($values as $key => $value): ?>

		                            <tr>
		                                <td><?= $value['product_name'] ?></td>
		                                <td><?= $value['product_price'] ?> грн.</td>
		                                <td><?= $value['quantity'] ?> шт.</td>
		                                <td><?= $value['product_price'] * $value['quantity'] ?> грн.</td>
		                                <td><?= Html::a(Service::findOne($value['product_serv_id'])->name, Url::to(Service::findOne($value['product_serv_id'])->link, true), ['target' => '_blank']); ?></td>
		                            </tr>
                                        <?php $summ_all += $value['product_price'] * $value['quantity']; ?>
                                    <?php endforeach;?>
                                <tfooter>
                                    <tr>
                                        <th colspan="6">Загальна сума: <?=$summ_all?> грн. </th>
                                    </tr>
                                </tfooter>
                            </table>
                        </div>
	                </li>
	            	<?php endforeach;?>
                </ul>
                <?php }  else { ?>
                    <h1>Замовлення відсутні</h1>
                <?php }?>
	        </div>
	    </div>
    </div>
</div>

views/settings/profile.php
<?php

/*
 * This file is part of the Dektrium project.
 *
 * (c) Dektrium project <http://github.com/dektrium>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

use yii\helpers\Html;
use dektrium\user\helpers\Timezone;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/**
 * @var yii\web\View $this
 * @var yii\widgets\ActiveForm $form
 * @var dektrium\user\models\Profile $model
 */

$this->title = "Налаштування профілю";
$this->params['breadcrumbs'][] = $this->title;
?>

<?= $this->render('/_alert', ['module' => Yii::$app->getModule('user')]) ?>

<div class="row">
    <div class="col-md-3">
        <?= $this->render('_menu') ?>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?= Html::encode($this->title) ?>
            </div>
            <div class="panel-body">
                <?php $form = ActiveForm::begin([
                    'id' => 'profile-form',
                    'options' => ['class' => 'form-horizontal'],
                    'fieldConfig' => [
                        'template' => "{label}\n<div class=\"col-lg-9\">{input}</div>\n<div class=\"col-sm-offset-3 col-lg-9\">{error}\n{hint}</div>",
                        'labelOptions' => ['class' => 'col-lg-3 control-label'],
                    ],
                    'enableAjaxValidation' => true,
                    'enableClientValidation' => false,
                    'validateOnBlur' => false,
                ]); ?>

                <?= $form->field($model, 'name')->label('Прізвище Ім\'я') ?>

                <?= $form->field($model, 'public_email')->label('Email') ?>

                <?= $form->field($model, 'website')->label('Веб сторінка') ?>

                <?php /* $form->field($model, 'location')->label('Місце знаходження') */?>

                <?php /*$form
                    ->field($model, 'timezone')
                    ->dropDownList(
                        ArrayHelper::map(
                            Timezone::getAll(),
                            'timezone',
                            'name'
                        )
                    ); */ ?>

                <?= $form->field($model, 'bio')->textarea()->label('Інформація про себе') ?>

                <div class="form-group">
                    <div class="col-lg-offset-3 col-lg-9">
                        <?= Html::submitButton('Зберегти', ['class' => 'btn btn-block btn-success']) ?>
                        <br>
                    </div>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>