controllers/CartController.php
<?php

namespace app\controllers;

use app\models\History;
use yii\web\Controller;
use app\models\Product;
use app\models\Cart;
use app\models\Order;

use Yii;

class CartController extends Controller {

	public function actionIndex() {
		$session = Yii::$app->session;
		$session->open();
		return $this->render('index', compact('session'));
	}

	public function actionAdd() {

		if (Yii::$app->request->isAjax){
			$id = Yii::$app->request->get('id');
			if (Product::findOne($id)) {
				$qty = (int)Yii::$app->request->get('qty');
				if (($qty = intval($qty)) && ($qty > 0)) {
					$product = Product::findOne($id);
					$session = Yii::$app->session;
					$session->open();
					$cart = new Cart();
					if(!empty($product)) {
						$cart->addToCart($product, $qty);
					}
					$this->layout = false;
					$qty = empty($session['cart.qty']) ? 0 : $session['cart.qty'];
					return json_encode(array(
						'cart_count'=> $qty,
						'cart_html'=> $this->render('index', compact('session'))
					));
				}
			}
		}
		else{
			return $this->redirect(['site/error']);
		}
	}

	public function actionClear() {
		if (Yii::$app->request->isAjax){
			$session = Yii::$app->session;
			$session->open();
			$session->remove('cart');
			$session->remove('cart.qty');
			$session->remove('cart.sum');
			$this->layout = false;
			$qty = empty($session['cart.qty']) ? 0 : $session['cart.qty'];
			return json_encode(array(
				'cart_count'=> $qty,
				'cart_html'=> $this->render('index', compact('session'))
			));
		}
		else{
			return $this->redirect(['site/error']);
		}
	}

	public function actionDel(){

		if (Yii::$app->request->isAjax){
			$id = Yii::$app->request->get('id');
			if (Product::findOne($id)) {
				$session = Yii::$app->session;
				$session->open();
				$cart = new Cart();
				$cart->recalc($id);
				$this->layout = false;
				$qty = empty($session['cart.qty']) ? 0 : $session['cart.qty'];
				return json_encode(array(
					'cart_count'=> $qty,
					'cart_html'=> $this->render('index', compact('session'))
				));
			}
		}
		else{
			return $this->redirect(['site/error']);
		}
	}

	public function actionChange(){
		if (Yii::$app->request->isAjax){
			$id = Yii::$app->request->get('id');
			if (Product::findOne($id)) {
				$qty = (int)Yii::$app->request->get('qty');
				if ((($qty = intval($qty)) && ($qty > 0))) {
					$qty = $qty;
				}
				else{
					$qty = 1;
				}
				$product = Product::findOne($id);
				$session = Yii::$app->session;
				$session->open();
				$cart = new Cart();
				if(!empty($product)) {
					$cart->changeToCart($product, $qty);
				}
				$this->layout = false;
				$qty = empty($session['cart.qty']) ? 0 : $session['cart.qty'];
				return json_encode(array(
					'cart_count'=> $qty,
					'cart_html'=> $this->render('index', compact('session'))
				));
			}		
		}
		else{
			return $this->redirect(['site/error']);
		}
	}

	public function actionConfirm() {
  		if (Yii::$app->request->isAjax) {

   			$session = Yii::$app->session;

   			if (!(\Yii::$app->user->isGuest)) {

				if ((History::myBalance(\Yii::$app->user->id))>-3000) {

	    			if (isset($session['cart'])) {

	     				foreach ($session['cart'] as $key => $value) {
	     					
	     					$order = new Order();
						    $order->date = date("Y:m:d");
						    $order->user_id = \Yii::$app->user->id;
						    $order->product_id = $key;
						    $order->quantity = $value['qty'];
						    $order->product_name = $value['name'];
						    $order->product_price = $value['price'];
						    $order->product_serv_id = $value['service_id'];
						    $order->save();

	                        $history = new History();
	                        $history->orders_id = $order->id;
	                        $history->summa = -($order->quantity * $value['price']);
	                        $history->operation = 1;
	                        $history->users_id = $order->user_id;
	                        $history->date = date("Y:m:d");
	                        $history->save();
	    
	     				}

						$session->open();
						$session->remove('cart');
						$session->remove('cart.qty');
						$session->remove('cart.sum');
						$this->layout = false;
						$qty = empty($session['cart.qty']) ? 0 : $session['cart.qty'];
						return json_encode(array(
							'cart_count'=> $qty,
							'cart_html'=> $this->render('index', compact('session'))
						));
	    			} 
	    			
	    			else {
	    			}
	    		}
	    		else {
	    			return json_encode(array(
	    				'balance' => History::myBalance(\Yii::$app->user->id)
					));
	    		}
    		}
   			else { 	
			}
   		}
		else $this->redirect(['site/error']);
	}
}

controllers/CategoryController.php
<?php

namespace app\controllers;
use app\models\Product;
use Yii;

use yii\web\Controller;

class CategoryController extends Controller {

	public function actionIndex($service_id) {
		$top = Product::find()->asArray()->select('category')->where(['serv_id' => $service_id, 'date_add' => date("Y-m-d")])->distinct()->all();
        if (!isset($top[0])) {
            return $this->render('message');
        }
		$category = $top[0]['category'];
		$products = Product::find()->asArray()->where(['category' => $category, 'date_add' => date("Y-m-d")])->all();

		foreach ($products as $key => $value) {
			$new_arr[$value['sub_category']][]=$value;
		}
		return $this->render('index', compact('new_arr', 'category', 'top'));
	}

	public function actionView() {
		$category = Yii::$app->request->get('category');
        $service_id = Yii::$app->request->get('service_id');
		//$id = Product::find()->select('serv_id')->where(['category' => $category])->distinct()->one();
		$products = Product::find()->asArray()->where(['category' => $category, 'date_add' => date("Y-m-d")])->all();
        $top = Product::find()->asArray()->select('category')->where(['serv_id' => $service_id, 'date_add' => date("Y-m-d")])->distinct()->all();
		foreach ($products as $key => $value) {
			$new_arr[$value['sub_category']][]=$value;
		}
		return $this->render('view', compact('new_arr', 'category', 'top'));
	}

	public function actionSearch($service_id){
        $params = trim(Yii::$app->request->get('query'));
        //$id_service = trim(Yii::$app->request->get('id'));
        $params=strip_tags($params);
        $service_id = strip_tags($service_id);
        if (Yii::$app->request->get('query') != $params){
            $this->redirect(\yii\helpers\Url::to(['category/search', ['service_id'=>$service_id, 'query'=>$params]]));
        }

        if ($params!='') {
            $products = Product::find()->asArray()->where(['like', 'sub_category', $params])
                ->orWhere(['like', 'product_name', $params])
                ->andWhere(['serv_id' => $service_id])
                ->all();
            foreach ($products as $key => $value) {
                $new_arr[$value['sub_category']][] = $value;
            }
            return $this->render('view', compact('new_arr', 'service_id'));
        }
        else $this->redirect(\yii\helpers\Url::to(['@web/index.php']));

    }
}

controllers/ProductController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\models\Product;
use Yii;

class ProductController extends Controller {
	public function actionView($id){
		$id = Yii::$app->request->get('id');
        $service_id = Yii::$app->request->get('service_id');
		$category = Product::find()->select('category')->where(['id' => $id])->distinct()->one();
		$id_service = Product::find()->select('serv_id')->where(['category' => $category])->distinct()->one();
        $top = Product::find()->asArray()->select('category')->where(['serv_id' => $service_id, 'date_add' => date("Y-m-d")])->distinct()->all();
		$product = Product::findOne($id);
		return $this->render('view', compact('product', 'category', 'id_service','top'));
	}
}

views/category/index.php
<?php

use yii\helpers\Html;

$this->title = 'Категорії';
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="row">
        <div class="col-lg-12">
            <form method="get" action="<?=\yii\helpers\Url::to(['category/search']) ?>" class="input-group">
                <input type="hidden" class="form-control" name="service_id" value="<?=Yii::$app->request->get('service_id')?>">
                <input type="text" class="form-control" name="query" placeholder="Введіть дані для пошуку">

                <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Шукати">
                    </span>
            </form>
            <ul class="categories_wrap">
            <?php if(isset($top)){ ?>
            <?php foreach ($top as $key => $value):?>
                <li class="categori_wrap">
                    <a href="<?php echo \yii\helpers\Url::to(['category/view','service_id'=>Yii::$app->request->get('service_id'), 'category' => $value['category']])?> ">
                        <div>
                            <?php
                                $img_name = 'images/'.$value['category'].'.png';
                                $img_name = mb_convert_encoding($img_name, 'UTF-8');

                                if (is_file($img_name)) {
                                    ?>
                                    <img src="/images/<?php echo $value['category'] ?>.png" alt="<?php echo $value['category'] ?>">
                                    <?php
                                } else {
                                     ?>
                                    <img src="/images/new.png" alt="<?php echo $value['category'] ?>">
                                    <?php
                                }
                            ?>
                        </div>
                        <span><?php echo $value['category'] ?></span>
                    </a>
                </li>
            <?php endforeach;?>
            </ul>
            <?php } ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="categori_content_wrap">
<?php if(!empty($new_arr)):?>
                <div class="categori_title">
                    <h1><?php echo $category?></h1>
                </div>
    <div class="subcategori_list">
        <ul class="clearfix">
            <?php foreach ($new_arr as $key => $value):?>
                <?php if (!empty($key)) : ?>
                <li><a href="#"><?php echo $key?></a></li>
                <?php endif;?>
            <?php endforeach;?>
        </ul>
    </div>

    <?php foreach ($new_arr as $key => $value):?>
                <div class="subcategori_content_wrap">
                    <?php if (!empty($key)) : ?>
                    <div class="subcategori_title">
                        <h2><?php echo $key?></h2>
                    </div>
                    <?php endif;?>
                    <div class="categori_content">
                        <ul>
    <?php foreach ($value as $key => $value):?>
                            <li>
                                <div class="catalog_product_wrap">
                                    <a href="<?= \yii\helpers\Url::to(['product/view', 'service_id'=>Yii::$app->request->get('service_id'), 'category' => Yii::$app->request->get('category'),
                                        'id'=>$value['id']])?>">
                                        <div class="catalog_product_img">
                                            <img src="<?php 
                                            if (!empty($value['photo_url'])){
                                                echo $value['photo_url']; 
                                            }
                                            else {  
                                                echo "/images/no_img.png";
                                            }
                                            ?>" alt="<?php echo $value['product_name']?>">
                                            <div class="hidden_info">
                                                <p><?php echo $value['description']?></p>
                                            </div>
                                        </div>
                                        <div class="catalog_product_info_wrap">
                                            <p class="catalog_product_subcategori_title"><?php echo $value['sub_category']?></p>
                                            <h3><?php echo $value['product_name']?></h3>
                                            <p class="catalog_product_info"><?php echo $value['weight']?></p>
                                        </div>
                                        <div class="catalog_product_price">
                                            <p><?php echo $value['price']?><span> грн.</span></p>
                                        </div>
                                    </a>
                                    <div class="catalog_product_footer clearfix">
                                        <a class='add_to_cart' data-id='<?php echo $value['id']?>' href="<?= \yii\helpers\Url::to(['cart/index', 'id'=>$value['id']])?>">Замовити</a>
                                        <div class="catalog_product_quantity">
                                            <input class='qty' type="text" value="1" maxlength="3">
                                            <span class="plus"></span>
                                            <span class="minus"></span>
                                            <span class="unit">шт.</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
<?php endforeach;?>
                        </ul>
                    </div>
                </div>
<?php endforeach;?>
<?php endif;?>
            </div>
        </div>
    </div>

views/category/message.php
<?php

use yii\helpers\Html;


$this->title = 'Категорії';
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="row">
        <div class="col-lg-12">
            <div class="message_category_wrap">
                <div class="message_category">
                    <p>Вибачте</p>
                    <p>Cервіс недоступний.</p>
                    <p>Cкористайтесь, <span>будь-ласка</span>, іншим</p>
                </div>
            </div>
        </div>
    </div>

views/category/view.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;

$this->title = 'Каталог';
$this->params['breadcrumbs'][] = ['label' => 'Категорії', 'url' => ['category/index', 'service_id' => Yii::$app->request->get('service_id')]];

// $this->params['breadcrumbs'][] = ['label' => 'Категорії', 'url' => ['category/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="row">
        <div class="col-lg-12">
            <form method="get" action="<?=\yii\helpers\Url::to(['category/search']) ?>" class="input-group">
                <input type="hidden" class="form-control" name="service_id" value="<?=Yii::$app->request->get('service_id')?>">
                <input type="text" class="form-control" name="query" placeholder="Введіть дані для пошуку">
                <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Шукати">
                    </span>
            </form>
            <?php if(isset($top)){ ?>
            <ul class="categories_wrap">
                <?php foreach ($top as $key => $value):?>
                    <li class="categori_wrap">
                        <a href="<?php echo \yii\helpers\Url::to(['category/view','service_id'=>Yii::$app->request->get('service_id'), 'category' => $value['category']])?> ">
                            <div>
                                <?php
                                $img_name = 'images/'.$value['category'].'.png';
                                $img_name = mb_convert_encoding($img_name, 'UTF-8');

                                if (is_file($img_name)) {
                                    ?>
                                    <img src="/images/<?php echo $value['category'] ?>.png" alt="<?php echo $value['category'] ?>">
                                    <?php
                                } else {
                                    ?>
                                    <img src="/images/new.png" alt="<?php echo $value['category'] ?>">
                                    <?php
                                }
                                ?>
                            </div>
                            <span><?php echo $value['category'] ?></span>
                        </a>
                    </li>
                <?php endforeach;?>
            </ul>
            <?php } ?>
            <div class="categori_content_wrap">
<?php if(!empty($new_arr)){?>
                <div class="categori_title">
                    <h1><?=isset($category)?$category:'' ?></h1>
                </div>
    <div class="subcategori_list">
        <ul class="clearfix">
            <?php foreach ($new_arr as $key => $value):?>
                <?php if (!empty($key)) : ?>
                <li><a href="#"><?php echo $key?></a></li>
                <?php endif;?>
            <?php endforeach;?>
        </ul>
    </div>
<?php foreach ($new_arr as $key => $value):?>
                <div class="subcategori_content_wrap">
                    <?php if (!empty($key)) : ?>
                    <div class="subcategori_title">
                        <h2><?php echo $key?></h2>
                    </div>
                    <?php endif;?>
                    <div class="categori_content">
                        <ul>
    <?php foreach ($value as $key => $value):?>
                            <li>
                                <div class="catalog_product_wrap">
                                    <a href="<?= \yii\helpers\Url::to(['product/view',
                                        'service_id'=>Yii::$app->request->get('service_id'), 'category' => Yii::$app->request->get('category'),
                                        'id'=>$value['id']])?>">
                                        <div class="catalog_product_img">
                                            <img src="<?php 
                                            if (!empty($value['photo_url'])){
                                                echo $value['photo_url']; 
                                            }
                                            else {  
                                                echo "/images/no_img.png";
                                            }
                                            ?>" alt="<?php echo $value['product_name']?>">
                                            <div class="hidden_info">
                                                <p><?php echo $value['description']?></p>
                                            </div>
                                        </div>
                                        <div class="catalog_product_info_wrap">
                                            <p class="catalog_product_subcategori_title"><?php echo $value['sub_category']?></p>
                                            <h3><?php echo $value['product_name']?></h3>
                                            <p class="catalog_product_info"><?php echo $value['weight']?></p>
                                        </div>
                                        <div class="catalog_product_price">
                                            <p><?php echo $value['price']?><span> грн.</span></p>
                                        </div>
                                    </a>
                                    <div class="catalog_product_footer clearfix">
                                        <a class='add_to_cart' data-id='<?php echo $value['id']?>' href="<?= \yii\helpers\Url::to(['cart/index', 'id'=>$value['id']])?>">Замовити</a>
                                        <div class="catalog_product_quantity">
                                            <input class='qty' type="text" value="1" maxlength="3">
                                            <span class="plus"></span>
                                            <span class="minus"></span>
                                            <span class="unit">шт.</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
<?php endforeach;?>
                        </ul>
                    </div>
                </div>
<?php endforeach;?>
<?php }
else echo "<h1>Нічого не знайдено!</h1>"
?>
            </div>
        </div>
    </div>